### PR TITLE
Updated DSP data and icons

### PR DESCRIPTION
**Pull request by glcoder**
Dyson Sphere Program updated recipes and items names, icons colors and categories icons.

### CODE REVIEW

**Comment by dcbroad3** [comment]
Thanks for the submission! The icon color codes and the ids look much nicer in this. How did you build it? Don't see anything that seems related in your github.

On mobile, but I'll review this fully as soon as possible.

**Comment by glcoder** [comment]
For icons i've used [UtinyRipper](mafaca/UtinyRipper) to extract assets, and then image-magick to create atlas:
```shell
magick montage ^
  DSPGAME/Assets/Resources/ui/textures/sprites/icons/component-icon.png ^
  DSPGAME/Assets/Resources/ui/textures/sprites/icons/factory-icon.png ^
  DSPGAME/Assets/Resources/icons/itemrecipe/*.png ^
  -geometry 64x64+0+0 -background transparent ^
  png32:icons.png
```

Then simple python script to calculate median colors:
```python
import os
import json
import numpy as np
from skimage import io

ICONS_PATH = "DSPGAME/Assets/Resources/icons/itemrecipe"
ATLAS_PATH = "DSPGAME/Assets/Resources/icons/icons.png"
INDEX = 2
ICONS = [
    {
        "color": "#FFFFFF",
        "id": "components",
        "position": "0px 0px"
    },
    {
        "color": "#FFFFFF",
        "id": "buildings",
        "position": "-64px 0px"
    },
]

for filename in os.listdir(ICONS_PATH):
    if not filename.endswith(".png"):
        continue

    file_path = os.path.join(ICONS_PATH, filename)
    img = io.imread(file_path)[:, :, :-1]
    average = img.mean(axis=0).mean(axis=0)

    icon = {
        "color": "#%02X%02X%02X" % (int(average[0]), int(average[1]), int(average[2])),
        "id": filename[:-4].lower(),
        "position": "%dpx %dpx" % (-64 * int(INDEX % 13), -64 * int(INDEX / 13))
    }

    ICONS.append(icon)
    INDEX = INDEX + 1

print(json.dumps(ICONS))
```

The items and recipes was done mostly by hands, I'm still looking how to automate this but it seens impossible to do atm. I've got an idea to parse DSP wiki https://dsp-wiki.com/, but it is still in development. Maybe I can contact developers and they will provide some recipes data in text format alongside game files.

Because of a lot of manual editing data.json will probably contains some incorrect data, I've tried to check all recipes, but without automated tests it's easy to overlook something. For instance I've already realized that I've forgot to update stack counts on items, will do this right now.

**Comment by dcbroad3** [comment]
@shadowtheage was able to use his tools to build the current data set, but wasn't able to get a lot of info like electricity usage, belt speed, etc. I talked with the wiki author and they said they wiki is being maintained manually also. Ideally it would benefit the community to get raw game data in some scripted or supported way.

**Comment by glcoder** [comment]
Yep, I've took data.json created by @ShadowTheAge and basically make my changes over it, except that I've used names from game assets for easy icon integration.

**Comment by ShadowTheAge** [comment]
I can give my scripts that I use to get data from DSP. It requires exporting files from the game using https://github.com/DerPopo/UABE
There are files for items, recipes, veins and strings (localization)

There are also files for buildins but one per building and so I decided to just hardcode that few metadata like belt speeds (there are 3)

data.json has to be generated automatically. They change some small things several times per week.

Currently they don't have string ids for buildings and only numeric. That will definitely change when they go for mod support.

As for icon colors - I can generate those but what are they used for?

**Comment by ShadowTheAge** [comment]
I will check UTinyRipper and maybe it can export those files also and do it in an automatic way

**Comment by glcoder** [comment]
UABE or UTinyRipper I think there's no big difference. Icon colors used for Sankey diagrams.

**Comment by ShadowTheAge** [comment]
if UTinyRipper can extract the same data (thats not images! That is serialized c# classes, it is harder) and has command line tool, It will be better for automation

**Comment by glcoder** [comment]
uTinyRipper has command line utility but it laks needed functionality. But GUI tool can extract prefabs and textures.

I've made a python script to process extracted data in a semi-automatic way (you still need to launch uTinyRipper GUI tool and generate icons.png using ImageMagick) [GenerateDataDSP.py](https://gist.github.com/glcoder/44f33a9d1b5b9618a44fbe81af9ebda0).

Later I will create repo for this tool with some refactoring in mind.

**Comment by ShadowTheAge** [comment]
I have tested uTinyRipper (gui) and it was unable to parse c# serialized classes, so no info about recipes/etc.

**Comment by glcoder** [comment]
> I have tested uTinyRipper (gui) and it was unable to parse c# serialized classes, so no info about recipes/etc.
> But in your export it seems like it is working

I've used prebuilt version of uTinyRipper and it seems working perfectly normal. Extracted resources that I used:

- `Assets/Resources/prototypes` all items and recipes data.
- `Assets/Resources/entities/prefabs` info about some buildings.
- `Assets/Resources/icons` items and buildings icons.
- `Assets/Resources/ui/textures/sprites/icons` UI icons.

> Also some gotchas (check that these are correct):
> 
> * Pump has speed of 50/min plus mining speed
> * Mining time on veins isnot used. Mining time equals to 30/min plus mining speed for every vein.

Will check this. But, correct me if I'm wrong, you can't configure veins count in factorio-lab so mining speed always be incorrect?

**Comment by ShadowTheAge** [comment]
My solution is to show vein count, not miner count
https://shadowtheage.github.io/factorio-lab/list#z=eJw9zDsKwEAIRdHdWJgp3nM+JIXbCdiFyf4hDiSx8SByLw8CVYdEqqIrS9DQ3j2UMn3aoWEVrUzbf41PBH+yJ7Mop2dhHeV2zRdsq7KG2vAAtn8b5Q==

**Comment by glcoder** [comment]
> My solution is to show vein count, not miner count

This could do the trick, I need to think about this.

**Comment by ShadowTheAge** [comment]
There is also one more such trick. Fractionator recipe depends on in/out belt speed so I added "belt" as a crafter used for fractionating

https://shadowtheage.github.io/factorio-lab/list#z=eJw9zDsKgEAMBNDbpIhbzGQ/aJHrCOlkvT+YBXWaeYQwlwdp1CGRqujKEjS0t4dSpk87NKyilWn7r/GJ4E/2JFDl9FxYR7ld8wXbWlmhNjy29Rvm

**Comment by glcoder** [comment]
> Fractionator recipe is also very special in how it is configured. It will not be correct if you just read it from recipes proto set (it looks like it wastes hydrogen there while it actually converts it 1:1 to deuterium but slowly)

From disassembled code it looks like it converts 1 hydrogen to 1 deuterium on success (1% chance), othervise it does nothing - just pass hydrogen through. This process does not implemented in script presented above. It's pretty close to that Kovarex enrichment process in Factorio do, so recipe 100 hydrogen -> 99 hydrogen + 1 deuterium will do fine. The belt speed must be considerate.

**Comment by ShadowTheAge** [comment]
> so recipe 100 hydrogen -> 99 hydrogen + 1 deuterium will do fine

No, it will show enormous amounts of hydrogen production and throw, for example, required belt amounts way off.

**Comment by glcoder** [comment]
> No, it will show enormous amounts of hydrogen production and throw, for example, required belt amounts way off.

Why you think that amount of hydrogen produced is a problem? It shows how much hydrogen system should get to actually produce 1 deuterium from that much of hydrogen, it's not a problem it's a correct recipe.

Just check actual Factorio recipe for uranium processing https://factoriolab.github.io/list#p=uranium-235*1&s=*kovarex-enrichment-process Actual recipe - 0.7% chance to produce 1 uranium-235 from 10 uranium ore. Same here.

**Comment by ShadowTheAge** [comment]
Yes and it shows 5700 miners to get 1/s u235. Which is not correct.
The actual recipe is 1 hydrogen to 1 deuterium, 99 more hydrogen is just a catalyst.

**Comment by glcoder** [comment]
> Yes and it shows 5700 miners and 95 belts to get 1/s u235. Which is not correct.

That's totally correct if you want to get 1/s u235 (at median) you must make the system with that much throughput, that's why you want to research and launch Kovarex Enrichment Process before building Nuclear Reactors all around. Same for DSP. Why you think wthis is incorrect?

You can check this in other calculator if you yhink this one contains an error https://kirkmcdonald.github.io/calc.html#data=1-1-19&rate=s&k=off&items=uranium-235:r:1

**Comment by ShadowTheAge** [comment]
Sorry, I thought you were talking about Kovarex. Well, then it is not that similar to the uranium processing, because uranium processing produces outputs that are not equal to inputs. It is similar to kovarex, however.

**Comment by glcoder** [comment]
I've update convert script and data.json to support veins count and fractionate recipe as I see it.

> Sorry, I thought you were talking about Kovarex. Well, then it is not that similar to the uranium processing, because uranium processing produces outputs that are not equal to inputs. It is similar to kovarex, however.

It is similar to Uranium Processing in a way that at median you'll get 99 hydrogen and 1 deuterium at the speed of belt. In Uranium Processing you'll get at median 1 u235 and about 143 u238 at the fixed speed. The inputs are different sure, but it's irrelevant for this case. In fact the only problem is that we don't know the underlying belt speed to correct the processing time. I think the proper soultion is to add a flag with supporting code to correct craft time accordingly.

@dcbroad3 is it possible to add functionality to pass belt speed to craft station and add a boolean flag to factory config which will multiply craft speed by belt speed?

**Comment by dcbroad3** [comment]
> @dcbroad3 is it possible to add functionality to pass input belt speed to craft station and add a boolean flag to factory config which will multiply craft speed by belt speed?

Technically, yes. The complicated thing is that, at least in Factorio, a recipe might have many inputs, each using a different belt, so the calculator wouldn't necessarily know which belt to use in this case. Would it be safe enough for now to just use the first input's belt speed, or should it do something more intelligent such as use the slowest of all the input belt speeds?

**Comment by ShadowTheAge** [comment]
I would say that is not what should be dont here.
For example I use the fastest availible belt to do fractionating as it is faster. That is not however my belt used for hydrogen output for some other row.
Doing like this will add a not-obvious dependency betwen lines

I think that my solution that just adds "factory" information to belts is better

**Comment by dcbroad3** [comment]
> I think that my solution that just adds "factory" information to belts is better

I think I agree here. My alternate suggestion was just going to be to add different versions of the factory for each belt, but this seems slightly more elegant this way.

**Comment by glcoder** [comment]
> I think I agree here. My alternate suggestion was just going to be to add different versions of the factory for each belt, but this seems slightly more elegant this way.

Well, this solution is simpler of course. I don't think it's a correct one tho, from the side of user experience at least. Anyway I've implemented this in the convert script and updated data.json in branch.

**Comment by dcbroad3** [comment]
One possible hack would be to treat the belt as a "module" - there is code in place for modules to affect factory speed, so the belt could be treated like a speed module. But if course this might look awkward in some places in the ui.

**Comment by glcoder** [comment]
> One possible hack would be to treat the belt as a "module" - there is code in place for modules to affect factory speed, so the belt could be treated like a speed module. But if course this might look awkward in some places in the ui.

Hm, iteresting soultion, I'll try it and get back to you.

**Comment by glcoder** [comment]
The module solution is looking good at first glance:
image
image

**Comment by glcoder** [comment]
I've changed fractionation to support belts as modules (and fixed craft speed). I guess this is a final version for now, alongside with [export script](https://gist.github.com/glcoder/44f33a9d1b5b9618a44fbe81af9ebda0). Later on I'll make separte repo for export tools.

**Comment by dcbroad3** [comment]
I will try to give this a full review later today or tomorrow.

**Comment by ShadowTheAge** [comment]
That will work until they add modules or something :D Good for now

**Comment by ShadowTheAge** [comment]
I still don't agree with fractionating being 100 hydrogen -> 99 hydrogen and 1 deuterium. While it is technically correct, noone places fractionators like this and the flow diagram becomes bloated

image

**Comment by glcoder** [comment]
> I still don't agree with fractionating being 100 hydrogen -> 99 hydrogen and 1 deuterium. While it is technically correct, noone places fractionators like this and the flow diagram becomes bloated

I agree that look of this is pretty harsh, but it's how this recipe works - floods your production with hydrogen (we are talking production per minute or even second here). If one wants a less amount of hydrogen he needs to use other ways to produce deuterium.

**Comment by ShadowTheAge** [comment]
But that is not how people do deuterium. They just make a loop of machines. One hydrogen belt in, one deuterium belt out. Hydrogen never goes in/out in huge amounts. Not used hydrogen just moves on a belt, it does not participate in the recipe.

here is my setup
image

**Comment by dcbroad3** [comment]
The same is generally true of kovarex in Factorio, though, but I've never seen any complaints about the appearance of the loop there. Still, I wouldn't necessarily be opposed to simplifying the recipe, down to 1 hydrogen -> 1 deuterium. This is effectively what it does. Part of the reason you can't do that safely in Factorio is productivity effects, but here it shouldn't matter.

**Comment by ShadowTheAge** [comment]
Thats true. Also productivity in Factorio only affects the extra, non-catalyst items. (I just tested that in your calculator and mine and got the same result)

There is however a difference: kovarex enrichement is only used for power and weapons (ie not in the main science factory) while hydrogen is used basically everywhere and in ever increasing amounts.

**Pull request merged**
