### PR TITLE
Fixed DSP mining rates and added gas giants recipes, closes #360, closes #361

### LINKED ISSUE #360: DSP - Hydrogen and Deuterium from Gas Giants
First of all: I love the DSP calculator, thanks a lot for supporting it here!

Would you please add a recipe to obtain Hydrogen and Deuterium from Gas Giants?
Seems like the calculator does not know Hydrogen and Deuterium can be mined as "basic resources" like ores and sulfuric acid but from gas giants.
If I remember correctly there are also Gas Giants for Fire Ice and Deuterium maybe add them as a recipe too.

I tried to calculate how to produce 60 Rockets per minute and disabled a lot of recipes. I tried to find the least complex solution by using all the "advanced resources" like fire ice and crystaline silicone for example. The calculator did it's best and made me produce 5000 excess Graphene as it was the only way to get enough hydrogen.

### LINKED ISSUE #361: DSP vein mining speed is incorrect
https://factoriolab.github.io/list#p=titanium-ore*2&s=dsp******1

Just noticed that something is wrong with vein mining data also. It should be 2 seconds to mine 1 titanium vein baseline
Every vein (except oil) is 0.5/s
It is correct for iron for example

There is a mining speed parameter for every vein but it is not used.

(I have +40% mining speed and placed a miner to touch one vein)
image

_Originally posted by @ShadowTheAge in https://github.com/factoriolab/factorio-lab/issues/358#issuecomment-771838832_

### PR DESCRIPTION
**Pull request by glcoder**
- Fixed mining rates for ores.
- Added gas giants mining recipes.
- Update [export script](https://gist.github.com/glcoder/44f33a9d1b5b9618a44fbe81af9ebda0).

### CODE REVIEW

**Comment by dcbroad3** [comment]
A few comments:

1. Was there a reason for the switch from 'components' and 'buildings' to 'component-icon' and 'factory-icon'? I personally preferred the old category IDs.
2. I note there is a new icon with the ID '1606' apparently for the gas giants. Could we give it a better ID than the numeric one? Also, it doesn't appear that the icon is used anywhere?
3. Was it intended that all numbers now have at least tenths precision? (e.g. 40 is now 40.0) This doesn't really matter either way, just making sure it's intentional.
4. Make sure that all "factory" objects that have "usage" and/or "drain" also contain the property "type": "electric". This is what broke power calculations before, "usage" is not factored into power unless "type" is "electric". You can check the current version for reference, I manually added this property to fix that bug.
5. It isn't necessary to specify the "moduleRank" property in the "defaults" any more, just leave it as "[]". The calculator will use the "minBelt" and "maxBelt" properties for DSP instead. (Can also see this in the current data.json)

**Comment by glcoder** [comment]
> A few comments:
> 
> 1. Was there a reason for the switch from 'components' and 'buildings' to 'component-icon' and 'factory-icon'? I personally preferred the old category IDs.

No reason besides orginal icon names from the game, for fully automatic spritesheet generation, I can revert this change.

> 2. I note there is a new icon with the ID '1606' apparently for the gas giants. Could we give it a better ID than the numeric one? Also, it doesn't appear that the icon is used anywhere?

It's the name of icon from the game, this is a gas mining research icon. It's used primarly as a temp icon for gas mining recipes, it has no usage on its own.

> 3. Was it intended that all numbers now have at least tenths precision? (e.g. 40 is now 40.0) This doesn't really matter either way, just making sure it's intentional.

It's not intenintnional I guess, I'll look into it.

> 4. Make sure that all "factory" objects that have "usage" and/or "drain" also contain the property "type": "electric". This is what broke power calculations before, "usage" is not factored into power unless "type" is "electric". You can check the current version for reference, I manually added this property to fix that bug.

Ok, will do.

> 5. It isn't necessary to specify the "moduleRank" property in the "defaults" any more, just leave it as "[]". The calculator will use the "minBelt" and "maxBelt" properties for DSP instead. (Can also see this in the current data.json)

Ok, I'll fix this.

**Comment by glcoder** [comment]
> 1. Was there a reason for the switch from 'components' and 'buildings' to 'component-icon' and 'factory-icon'? I personally preferred the old category IDs.

Fixed.

> 2. I note there is a new icon with the ID '1606' apparently for the gas giants. Could we give it a better ID than the numeric one? Also, it doesn't appear that the icon is used anywhere?

Fixed.

> 3. Was it intended that all numbers now have at least tenths precision? (e.g. 40 is now 40.0) This doesn't really matter either way, just making sure it's intentional.

Don't know why it's happened (if it's somehow been different before), I guess we can just ignore it.

> 4. Make sure that all "factory" objects that have "usage" and/or "drain" also contain the property "type": "electric". This is what broke power calculations before, "usage" is not factored into power unless "type" is "electric". You can check the current version for reference, I manually added this property to fix that bug.

Fixed. BUT! I've removed drain export, because it's messing up with acual energy usage. Also mining drills shows wrong energy consumption because of vein mining mehanics, calculator adds full mining drill energy usage for each vein, it's expected and understandable, but I don't know how to fix this by now.

> 5. It isn't necessary to specify the "moduleRank" property in the "defaults" any more, just leave it as "[]". The calculator will use the "minBelt" and "maxBelt" properties for DSP instead. (Can also see this in the current data.json)

Fixed.

**Comment by dcbroad3** [comment]
> Also mining drills shows wrong energy consumption because of vein mining mehanics, calculator adds full mining drill energy usage for each vein, it's expected and understandable, but I don't know how to fix this by now.

I think I missed this the first time: The existing solution to this problem is that we decided to take out the energy usage and drain on mining drills. So you can remove those properties.

**Comment by glcoder** [comment]
> I think I missed this the first time: The existing solution to this problem is that we decided to take out the energy usage and drain on mining drills. So you can remove those properties.

I've removed power usage from miners (veins, water, oil). Also I think it is neccesary to disable power drain for DSP mod, because DSP drain is just idle state energy consumption, it does not add up with working state energy consumption.

**Comment by dcbroad3** [comment]
Thanks for the work on this!

**Pull request merged**
