### PR TITLE
Add i18n support, closes #708

### LINKED ISSUE #708: Support for multiple languages

### PR DESCRIPTION
**Pull request by qq253498229**

### CODE REVIEW

**Comment by dcbroad3** [comment]
This is looking fantastic, I appreciate your work here. 
I'm not sure if you're ready for comments yet, but in general this is exactly the approach I would want to take with i18n. 
It looks like the test build fails bc the `package-lock.json` file is out of sync, can be fixed by `npm install`. I try to maintain 100% code coverage on this project, but it doesn't look like your changes will involve many changes to the TypeScript code so it's unlikely to require many changes to tests.

**Comment by qq253498229** [comment]
I'm so sorry, because of my bad habit, I forgot to submit the `package-lock.json` 。
I have no experience in angular unit testing. What should I do to solve these?

**Comment by dcbroad3** [comment]
As far as I know I can't commit directly to your PR, but I was able to get your tests fixed in a forked branch with this commit:
https://github.com/factoriolab/factorio-lab/commit/a36305700d53144ce04bfe2f43d43d9910010e61

**Comment by dcbroad3** [comment]
> [Revert column.ts, because it cause flow error](https://github.com/factoriolab/factorio-lab/pull/707/commits/8962bd5d981878144fa2e890eb9d197e5eb448dd)

Appreciate you leaving the translations in the JSON - I can likely resolve issues like this, but I don't know Chinese so the translations are extremely valuable regardless.

**Comment by qq253498229** [comment]
Thanks for add tests for me, I'm really not good at testing.
I was confused about some places, such as how to translate `src/data/1.1/data.json` , I wonder what you think of this part?

**Comment by dcbroad3** [comment]
Do you consider this ready, or can you let me know when you consider it ready?

**Comment by dcbroad3** [comment]
> Thanks for add tests for me, I'm really not good at testing. I was confused about some places, such as how to translate `src/data/1.1/data.json` , I wonder what you think of this part?

Translating the data in the json files will be tough. I'm not sure which way is the 'right' way to do it. I'm guessing it should be something like:

1. Set up a src/data/1.1/i18n/cn.json file
2. Use the same basic schema as data.json, but only include fields that need translated (maybe just `name`).
3. When picking a language other than English, use the spread operator to merge the json data, like `{ ...data, ...cn }`.
4. Use the merged data which should include only translated names

Alternately the schema should be changed to pull in all names from an external json file with a schema like your existing translation files, but that would require a ton of work. 

Frankly, it might be better to attempt that in a separate pr?

**Comment by qq253498229** [comment]
I did it for a while, and it seems no problem from the result. 
But I am not very clear about datasets lifecycle and the state of the project.

By the way, `datasets.effects.spec.ts` has been throwing exceptions. I tried to modify it, but it hasn't been successful.

**Comment by dcbroad3** [comment]
> I did it for a while, and it seems no problem from the result. But I am not very clear about datasets lifecycle and the state of the project.
> 
> By the way, `datasets.effects.spec.ts` has been throwing exceptions. I tried to modify it, but it hasn't been successful.

You've been busy! I'll try to look into the issue with the effects on your branch when I have some time.

**Comment by qq253498229** [comment]
Yeah, so far I have finished translating `dsp` and `1.1`. 
I will continue to translate `sfy` when I am free.

**Comment by dcbroad3** [comment]
> Yeah, so far I have finished translating `dsp` and `1.1`. I will continue to translate `sfy` when I am free.

Do you want to do the `sfy` work as a separate PR?

**Comment by dcbroad3** [comment]
When you're done translating the json files, could you minify them? I use:
https://codebeautify.org/jsonminifier
Just keeps diffs clean, don't want it to look like this project is 99% json.

**Comment by dcbroad3** [comment]
Is this ready to be merged from your point of view?

**Comment by qq253498229** [comment]
It's ready. There are still some details that I will submit PR later.

**Review by dcbroad3 — APPROVED** [review]

**Comment by dcbroad3** [comment]
> It's ready. There are still some details that I will submit PR later.

Thanks. I will merge it soon, when I have some free time to also verify everything is working as intended post-merge.

**Pull request merged**
